tap "homebrew/cask"
tap "homebrew/core"
brew "fzf"
brew "go"
brew "jq"
brew "gpg"
brew "hub"
brew "httpie"
brew "iperf"
brew "mas"
brew "ssh-copy-id"
brew "wget"
brew "zsh"
cask "chromedriver"
cask "dash"
cask "docker"
cask "dropbox"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "licecap"
cask "omnifocus"
cask "paw"
cask "spotify"
cask "sublime-text"
cask "transmit"
cask "virtualbox"
cask "vagrant"
cask "vlc"
cask "zoom"
mas "1Password 7 - Password Manager (7.2.2)", id: 1333542190  
mas "Alfred (1.2)", id: 405843582   
mas "Amphetamine (4.0.5)", id: 937984704   
mas "Bear (1.6.7)", id: 1091189122  
mas "DaisyDisk (4.6.5)", id: 411643860   
mas "Fantastical 2", id: 975937182   
mas "Kindle (1.23.2)", id: 405399194   
mas "Moom (3.2.13)", id: 419330170   
mas "OmniGraffle 7 (7.9.4)", id: 1142578753  
mas "Slack (3.3.3)", id: 803453959   
mas "Xcode (10.1)", id: 497799835   
